### ISSUE TITLE
не кликается, ни вручную ни скриптом

### ISSUE THREAD

**Issue by arm4xlll** [mudachyo/notcoin-bot#2]

**Comment by mudachyo** [comment]
Скрипт работает. А чтобы кликать вручную, нужно включить мобильный режим. На странице с коином нажми F12, а затем Ctrl + Shift + M
![Desktop3-17-202411-58-00PM-ezgif com-video-to-gif-converter](https://github.com/mudachyo/notcoin-bot/assets/25475399/1a329453-653e-49f4-9158-16c7cb54c737)
