### ISSUE TITLE
скрипт не запускается 

### ISSUE THREAD

**Issue by Crypto0VER** [mudachyo/notcoin-bot#3]
Пишу в консоль скрипт и браузер отвечает числом например "17" или другое какое-то и не понимаю почему не работает

**Comment by mudachyo** [comment]
Попробуй автоматический скрипт из последнего абзаца репозитория и отпиши работает он или нет
https://github.com/mudachyo/notcoin-bot#автоматический-запуск-скрипта

**Comment by mudachyo** [comment]
Если тебе нужна конкретно консольная версия, попробуй заменить в ней значение. `globalscore = 1000` на `globalscore = 900`
